# Generated by Django 4.2.20 on 2026-02-28 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_cadastros_assistenciais', '0001_initial'),
        ('admin_cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPassagemPlantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_passagem_plantao', models.CharField(max_length=80, verbose_name='Tipo de Passagem de Plantão')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento', verbose_name='Estabelecimento')),
                ('us_atualizacao', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipopassagem_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipopassagem_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Tipo de Passagem de Plantão',
                'verbose_name_plural': '1. Tipos de Passagem de Plantão',
            },
        ),
        migrations.CreateModel(
            name='ParametrosPassagemPlantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observações')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento', verbose_name='Estabelecimento')),
                ('profissao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros_assistenciais.profissao', verbose_name='Profissao Passagem Plantao')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profissional_passagem', to=settings.AUTH_USER_MODEL, verbose_name='Profissional Passagem Plantao')),
                ('tipo_passagem_plantao', models.ManyToManyField(help_text='As opções de tipos liberam os tipos que o usuário pode ver e cadastrar!', to='admin_passagem_plantao.tipopassagemplantao', verbose_name='Tipos de Passagem de Plantão')),
                ('tipo_passagem_plantao_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_passagem_plantao_padrao', to='admin_passagem_plantao.tipopassagemplantao', verbose_name='Tipo de Passagem Plantão Padrão')),
                ('us_atualizacao', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parpassagem_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parpassagem_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Parâmetros Passagem Plantão',
                'verbose_name_plural': '2. Parâmetros Passagens de Plantões',
                'ordering': ['-pk'],
            },
        ),
    ]
