# Generated by Django 4.2.20 on 2026-02-28 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='CRM/Coren/Etc', max_length=20, verbose_name='Número')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
            ],
            options={
                'verbose_name': 'Cadastro Profissional da Assistencia',
                'verbose_name_plural': '7. Cadastro de Profissionais da Assistencia',
                'ordering': ['profissional'],
            },
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(max_length=255)),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='especialidade_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='especialidade_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': '2. Especialidades',
                'ordering': ['especialidade'],
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnos', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite'), ('Diurno', 'Diurno'), ('Noturno', 'Noturno'), ('Integral', 'Integral')], max_length=20, verbose_name='Turnos')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turnos_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turnos_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Turnos Assistência',
                'verbose_name_plural': '6. Turnos Assistência',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ProfissionalEspecialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_especialidade', models.CharField(max_length=20, verbose_name='Número Reg.Esp.')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros_assistenciais.especialidade', verbose_name='Especialidade')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros_assistenciais.cadastroprofissional', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Especialidade do Profissional',
                'verbose_name_plural': 'Especialidades dos Profissionais',
                'unique_together': {('profissional', 'especialidade')},
            },
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissao', models.CharField(max_length=255, verbose_name='Profissão')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profissao_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profissao_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Profissão',
                'verbose_name_plural': '1. Profissões',
                'ordering': ['profissao'],
            },
        ),
        migrations.CreateModel(
            name='OrgaoRegulador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=100, verbose_name='Sigla Órgão Regulador')),
                ('descricao', models.CharField(max_length=100, verbose_name='descricao por Extenso')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estado', verbose_name='UF')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orgao_regulador_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orgao_regulador_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Orgão Regulador',
                'verbose_name_plural': '4. Orgãos Reguladores',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='CID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True, verbose_name='Código CID')),
                ('descricao', models.CharField(max_length=200, verbose_name='descricao Código CID')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cid_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cid_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'CID',
                'verbose_name_plural': '5. Classif CID',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='CBO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cbo', models.CharField(max_length=6, verbose_name='Código CBO')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição CBO')),
                ('escolaridade_minima', models.CharField(blank=True, max_length=100, null=True, verbose_name='Escolaridade Mínima')),
                ('salario_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Salário Médio')),
                ('area_atuacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área de Atuação')),
                ('habilidades_requeridas', models.TextField(blank=True, null=True, verbose_name='Habilidades Requiridas')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cbo_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cbo_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'CBO - Classificação Brasileira de Ocupações',
                'verbose_name_plural': '3. CBO - Classificação Brasileira de Ocupações',
                'ordering': ['descricao'],
            },
        ),
        migrations.AddField(
            model_name='cadastroprofissional',
            name='cbo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros_assistenciais.cbo', verbose_name='CBO'),
        ),
        migrations.AddField(
            model_name='cadastroprofissional',
            name='especialidades',
            field=models.ManyToManyField(blank=True, through='admin_cadastros_assistenciais.ProfissionalEspecialidade', to='admin_cadastros_assistenciais.especialidade', verbose_name='Especialidades'),
        ),
        migrations.AddField(
            model_name='cadastroprofissional',
            name='orgao_regulador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros_assistenciais.orgaoregulador', verbose_name='Orgão Regulador'),
        ),
        migrations.AddField(
            model_name='cadastroprofissional',
            name='profissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros_assistenciais.profissao', verbose_name='Profissão'),
        ),
        migrations.AddField(
            model_name='cadastroprofissional',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Associado ao Profissional'),
        ),
        migrations.AddField(
            model_name='cadastroprofissional',
            name='us_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cadastro_medico_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização'),
        ),
        migrations.AddField(
            model_name='cadastroprofissional',
            name='us_registro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cadastro_medico_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro'),
        ),
        migrations.AddConstraint(
            model_name='profissao',
            constraint=models.UniqueConstraint(fields=('profissao', 'status'), name='unique_profissao_status'),
        ),
        migrations.AddConstraint(
            model_name='orgaoregulador',
            constraint=models.UniqueConstraint(fields=('descricao', 'status'), name='unique_orgao_regulador_status'),
        ),
        migrations.AddConstraint(
            model_name='especialidade',
            constraint=models.UniqueConstraint(fields=('especialidade', 'status'), name='unique_especialidade_status'),
        ),
        migrations.AddConstraint(
            model_name='cbo',
            constraint=models.UniqueConstraint(fields=('codigo_cbo', 'status'), name='unique_cbo_status'),
        ),
        migrations.AddConstraint(
            model_name='cadastroprofissional',
            constraint=models.UniqueConstraint(fields=('profissional', 'status'), name='unique_cadmedicoass_status'),
        ),
    ]
