# Generated by Django 4.2.20 on 2026-02-28 20:50

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_cadastros_financeiros', '0001_initial'),
        ('admin_cadastros', '0001_initial'),
        ('admin_financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Cartão')),
                ('tipo', models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito')], default='CREDITO', max_length=10, verbose_name='Tipo de Cartão')),
                ('numero_cartao', models.CharField(max_length=20, unique=True, verbose_name='Número do Cartão (últimos 4 dígitos)')),
                ('bandeira', models.CharField(help_text='Ex: Visa, Mastercard, Elo, etc.', max_length=50, verbose_name='Bandeira')),
                ('limite', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Limite do Cartão')),
                ('dia_fechamento', models.PositiveIntegerField(default=10, help_text='Dia do mês em que a fatura é fechada', verbose_name='Dia de Fechamento')),
                ('dia_vencimento', models.PositiveIntegerField(default=20, help_text='Dia do mês em que a fatura vence', verbose_name='Dia de Vencimento')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('conta_bancaria', models.ForeignKey(help_text='Conta onde será feito o pagamento do cartão', on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros_financeiros.conta', verbose_name='Conta Bancária')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento', verbose_name='Estabelecimento')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='us_cartao_atualizacao', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='us_cartao_registro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cartão de Pagamento',
                'verbose_name_plural': '1. Cartões de Pagamento',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='ClassificacaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Classificacao do Fornecedor')),
                ('observacao', models.CharField(blank=True, max_length=80, null=True, verbose_name='Observações')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='us_classefornecedor_atualizacao', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='us_classefornecedor_registro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classificacao Fornecedor',
                'verbose_name_plural': '1. Classificação Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='FaturaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(help_text='Primeiro dia do mês da fatura', verbose_name='Mês de Referência')),
                ('data_fechamento', models.DateField(verbose_name='Data de Fechamento')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Total')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Pago')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('PAGA', 'Paga'), ('PARCIAL', 'Paga Parcialmente')], default='ABERTA', max_length=10, verbose_name='Status da Fatura')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='admin_pagamentos.cartaopagamento', verbose_name='Cartão')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='us_fatura_cartao_atualizacao', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='us_fatura_cartao_registro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fatura de Cartão',
                'verbose_name_plural': '3. Faturas de Cartão',
                'ordering': ['-mes_referencia'],
                'unique_together': {('cartao', 'mes_referencia')},
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Fornecedor')),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_pagamentos.classificacaofornecedor', verbose_name='Classificação Fornecedor')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_cadastros.empresa', verbose_name='Pessoa Jurídica')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_cadastros.pessoa', verbose_name='Pessoa Física')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='us_fornecedor_atualizacao', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='us_fornecedor_registro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': '3. Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='TransacaoCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Transação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('data_transacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Transação')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria')),
                ('fornecedor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fornecedor/Estabelecimento')),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Documento')),
                ('nota_fiscal', models.FileField(blank=True, null=True, upload_to='cartao/notas_fiscais/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'peg'])], verbose_name='Nota Fiscal')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='admin_pagamentos.cartaopagamento', verbose_name='Cartão')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='us_transacao_cartao_atualizacao', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='us_transacao_cartao_registro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação de Cartão',
                'verbose_name_plural': '2. Transações de Cartão',
                'ordering': ['-data_transacao'],
            },
        ),
        migrations.CreateModel(
            name='ParametrosPagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Previsto')),
                ('dia_pagamento', models.PositiveIntegerField(blank=True, help_text='Informe o dia do mês (1 a 31) para o pagamento. Para periodicidade semanal/quinzenal, será ignorado.', null=True, verbose_name='Dia do Pagamento')),
                ('recorrencia', models.CharField(choices=[('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('anual', 'Anual')], default='mensal', max_length=10, verbose_name='Recorrência')),
                ('data_inicio', models.DateField(help_text='Data inicial para geração das cobranças.', verbose_name='Início da Recorrência')),
                ('data_fim', models.DateField(blank=True, help_text='Data final para geração das cobranças. Deixe em branco para recorrência indefinida.', null=True, verbose_name='Fim da Recorrência')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True)),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_pagamentos.fornecedor', verbose_name='Fornecedor')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parametro_atualizacao', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parametro_registro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parâmetro de Pagamento',
                'verbose_name_plural': '4. Parâmetros de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='PagamentoCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor do Pagamento')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Pagamento')),
                ('forma_pagamento', models.CharField(help_text='Ex: Transferência, Débito, etc.', max_length=50, verbose_name='Forma de Pagamento')),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Documento')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='admin_pagamentos.faturacartao', verbose_name='Fatura')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='us_pagamento_cartao_atualizacao', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='us_pagamento_cartao_registro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento de Cartão',
                'verbose_name_plural': '4. Pagamentos de Cartão',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pagamento')),
                ('valor_saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo')),
                ('dt_vencimento', models.DateField(help_text='Informe o Vencimento', verbose_name='Data Vencimento')),
                ('forma_pagamento', models.CharField(choices=[('B', 'Boleto'), ('C', 'Cartão Crédito'), ('D', 'Cartão Débito'), ('P', 'Pix'), ('T', 'Transferência'), ('I', 'Dinheiro'), ('H', 'Cheque'), ('O', 'Outros')], default='A', max_length=1, verbose_name='Forma Pagamento')),
                ('nota_fiscal', models.CharField(blank=True, max_length=10, null=True)),
                ('anexo_boleto', models.FileField(blank=True, null=True, upload_to='pagamentos/boletos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'peg'])], verbose_name='Anexo Boleto')),
                ('anexo_nota_fiscal', models.FileField(blank=True, null=True, upload_to='pagamentos/notas_fiscais/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'peg'])], verbose_name='Anexo Nota Fiscal')),
                ('previsto_fechado', models.BooleanField(blank=True, help_text='Marque para fechado, desmarque para previsto!', null=True, verbose_name='Previsto ou Fechado?')),
                ('dt_liquidacao', models.DateField(blank=True, null=True, verbose_name='Data de Liquidação')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True)),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('classificacao_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_pagamentos.classificacaofornecedor', verbose_name='Classificação Pagamento')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_pagamentos.fornecedor', verbose_name='Fornecedor')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='us_pagamento_atualizacao', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='us_pagamento_registro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': '5. Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='ClassificacaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Classificacao do Pagamento')),
                ('observacao', models.CharField(blank=True, max_length=80, null=True, verbose_name='Observações')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='us_classepagto_atualizacao', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='us_classepagto_registro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classificacao Pagamento',
                'verbose_name_plural': '2. Classificação Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='BaixaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Pagamento')),
                ('dt_pagamento', models.DateField(verbose_name='Data do Pagamento')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True)),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('competencia_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_financeiro.competenciabancaria', verbose_name='Competência')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_pagamentos.pagamento', verbose_name='Pagamento')),
                ('transacao_financeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros_financeiros.transacaofinanceira', verbose_name='Transação Financeira')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='us_baixa_pagamento_atualizacao', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='us_baixa_pagamento_registro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Baixa de Pagamento',
                'verbose_name_plural': '6. Baixa de Pagamentos',
            },
        ),
    ]
