# Generated by Django 4.2.20 on 2026-02-28 20:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import dominios.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_faturas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_cadastros_assistenciais', '0001_initial'),
        ('admin_cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carater_atendimento', models.CharField(choices=[('E', 'Eletivo'), ('U', 'Urgência'), ('M', 'Emergência')], default='E', max_length=1, verbose_name='Caráter do Atendimento')),
                ('dt_atendimento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Atendimento')),
                ('dt_alta', models.DateTimeField(blank=True, null=True, verbose_name='Data de Alta')),
                ('tipo_alta', models.CharField(blank=True, choices=[('alta', 'Alta'), ('transferencia', 'Transferência'), ('obito', 'Óbito'), ('pedido', 'Pedido')], max_length=50, null=True, verbose_name='Tipo de Alta')),
                ('telefone_responsavel', models.CharField(blank=True, default='', max_length=14, null=True, verbose_name='Telefone do Responsável')),
                ('telefone_familiar', models.CharField(blank=True, default='', max_length=14, null=True, verbose_name='Telefone do Famíliar')),
                ('telefone_extra', models.CharField(blank=True, default='', max_length=14, null=True)),
                ('entidade_encaminhamento', models.CharField(choices=[('fundo_municipal_assistencia_social', 'Fundo Municipal de Assistência Social'), ('fundo_municipal_saude', 'Fundo Municipal de Saúde'), ('fundo_estadual_assistencia_social', 'Fundo Estadual de Assistência Social'), ('fundo_estadual_saude', 'Fundo Estadual de Saúde'), ('fundo_nacional_assistencia_social', 'Fundo Nacional de Assistência Social'), ('fundo_nacional_saude', 'Fundo Nacional de Saúde'), ('fundo_municipal', 'Fundo Municipal'), ('fundo_estadual', 'Fundo Estadual'), ('fundo_nacional', 'Fundo Nacional'), ('outros', 'Outros')], max_length=50, verbose_name='Entidade do Encaminhamento')),
                ('medicacao', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Uso de Medicação')),
                ('observacoes', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Observações')),
                ('autos_internacao', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Autos da Internação')),
                ('autos_curatela', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Autos da Curatela')),
                ('autos_cobranca', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Autos Cobrança')),
                ('anexo_um', models.FileField(blank=True, help_text='Adicione arquivos dos formatos PDF, JPG, JPEG, PNG.', null=True, upload_to='anexos/atendimento/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), dominios.utils.validate_anexo_file])),
                ('anexo_dois', models.FileField(blank=True, help_text='Adicione arquivos dos formatos PDF, JPG, JPEG, PNG.', null=True, upload_to='anexos/atendimento/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), dominios.utils.validate_anexo_file])),
                ('anexo_tres', models.FileField(blank=True, help_text='Adicione arquivos dos formatos PDF, JPG, JPEG, PNG.', null=True, upload_to='anexos/atendimento/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), dominios.utils.validate_anexo_file])),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('cert_nascimento', models.BooleanField(verbose_name='Certidão de Nascimento')),
                ('rg', models.BooleanField(verbose_name='RG')),
                ('cpf', models.BooleanField(verbose_name='CPF')),
                ('titulo_eleitor', models.BooleanField(verbose_name='Título de Eleitor')),
                ('carteira_vacina', models.BooleanField(verbose_name='Carteira de Vacina')),
                ('cartao_sus', models.BooleanField(verbose_name='Cartão SUS')),
                ('cartao_banco', models.BooleanField(verbose_name='Cartão Banco')),
                ('carteira_trabalho', models.BooleanField(verbose_name='CTPS Carteira de Trabalho')),
                ('foto', models.BooleanField()),
                ('outros', models.BooleanField()),
                ('cidade_encaminhamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamento_cidade', to='admin_cadastros.cidade', verbose_name='Cidade do Encaminhamento')),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_faturas.convenio', verbose_name='Convênio')),
                ('diagnostico_encaminhamento', models.ManyToManyField(blank=True, to='admin_cadastros_assistenciais.cid', verbose_name='CID - Diagnósticos dos encaminhamentos')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.pessoa', verbose_name='Pessoa')),
                ('pessoa_docentrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pessoa_documento_entrega', to='admin_cadastros.pessoa', verbose_name='Pessoa da Entrega de Documentos')),
                ('tipo_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.tipoatendimento', verbose_name='Tpo de Atendimento')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimento_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimento_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': '3.1 Atendimentos',
                'ordering': ['-id'],
            },
        ),
    ]
