# Generated by Django 4.2.20 on 2026-02-28 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('descricao', models.CharField(help_text='Descrição da categoria. Ex: Restrito hospitalar, etc. Recomendado para distinguir valores nas tabelas de preços de faturamento.', max_length=255, verbose_name='Descrição')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_registro', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Sub Categoria',
                'verbose_name_plural': '5. Categorias',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('descricao', models.CharField(help_text='Descrição da classe. Ex: analgésico, anti hipertensivo, equipos, dispositivos de acessos, etc.', max_length=255, verbose_name='Descrição')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_registro', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': '3. Classes',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('descricao', models.CharField(help_text='Descrição do grupo. Ex: Medicamento genérico, Medicamento Referência, Material Hospitalar, Material Geral ou de Escritório, etc.', max_length=255, unique=True, verbose_name='Descrição')),
                ('pode_ser_prescrito', models.BooleanField(default=False, help_text='Se marcado, todos os produtos relacionados ao grupo poderão ser prescrito em uma prescrição médica. Recomendado para medicamentos.', verbose_name='Grupo pode ser prescrito?')),
                ('grupo_de_medicamento', models.BooleanField(default=False, help_text='Marque para todos os grupos de medicamentos. Recomendado para medicamentos.', verbose_name='Grupo de medicamento?')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': '2. Grupos',
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('unidade_medida', models.CharField(help_text='Unidade de medida do produto. Ex: ml, mg, g, etc.', max_length=3, verbose_name='Unidade de Medida')),
                ('descricao', models.CharField(help_text='Descrição da unidade de medida. Ex: mililitro, miligrama, grama, etc.', max_length=255, verbose_name='Descrição')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_registro', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': '6. Unidades de Medidas',
            },
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('descricao', models.CharField(help_text='Descrição do tipo de produto. Ex: Medicamento, Material, etc.', max_length=255, unique=True, verbose_name='Descrição')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_registro', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Tipo de Produto',
                'verbose_name_plural': '1. Tipos de Produtos',
            },
        ),
        migrations.CreateModel(
            name='SubClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('descricao', models.CharField(help_text='Descrição da sub classe. Ex: inibidor, potencializador, equipo em bomba, equipo geral,  etc.', max_length=255, verbose_name='Descrição')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_estoques.classe')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_registro', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Sub Classe',
                'verbose_name_plural': '4. Sub Classes',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('descricao', models.CharField(max_length=32, verbose_name='Descrição')),
                ('via', models.CharField(choices=[('vo', 'VO'), ('ev', 'EV'), ('im', 'IM'), ('--', '--')], max_length=50, verbose_name='Via Administração')),
                ('principio_ativo', models.BooleanField(default=False, help_text='Se marcado, selecione o produto referência para este princípio ativo. Recomendado para medicamentos. Neste sistema tratamos o princípio ativo como o medicamento genérico, o item marcado como princípio ativo será o controlador do estoque')),
                ('pode_ser_prescrito', models.BooleanField(default=False, help_text='Se marcado, o produto poderá ser prescrito em uma prescrição médica. Caso pertença a um grupo marcado como pode ser prescrito, este não precisa ser marcado, ou seja, este campo é apenas para exceçoes do grupo. Recomendado para medicamentos.', verbose_name='Produto pode ser prescrito?')),
                ('observacao', models.CharField(blank=True, help_text='Observação sobre o produto. Ex: Produto de uso exclusivo para o setor de enfermagem, etc.', max_length=255, null=True, verbose_name='Observações gerais')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_estoques.categoria')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_estoques.classe', verbose_name='Classe')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_estoques.grupo', verbose_name='grupo')),
                ('produto_referencia', models.ForeignKey(blank=True, help_text='Se o produto for um princípio ativo, vincule o produto de referência aqui. Se o produto for um produto de referência, não vincule nada aqui. Recomendado para medicamentos.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto_referencia_produto', to='admin_estoques.produto')),
                ('subclasse', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='classe', chained_model_field='classe', null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_estoques.subclasse', verbose_name='subclasse')),
                ('unidade_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_estoques.unidademedida', verbose_name='Unidade de Medida')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_registro', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': '7. Produtos',
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='tipo_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_estoques.tipoproduto'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='us_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='us_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_registro', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(fields=('descricao', 'status'), name='unique_produto_status'),
        ),
    ]
