# Generated by Django 4.2.20 on 2026-02-28 20:50

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_cadastros_financeiros', '0001_initial'),
        ('admin_cadastros', '0001_initial'),
        ('admin_pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Caixa')),
                ('numero_caixa', models.CharField(max_length=20, unique=True, verbose_name='Número do Caixa')),
                ('observacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observações')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento', verbose_name='Estabelecimento')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixas_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='us_caixa_atualizacao', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='us_caixa_registro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': '1. Caixas',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='SaldoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_abertura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora de Abertura')),
                ('dt_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Fechamento')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Saldo Inicial')),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Saldo Final')),
                ('total_entradas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total de Entradas')),
                ('total_saidas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total de Saídas')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_tesouraria.caixa', verbose_name='Caixa')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='us_saldo_caixa_atualizacao', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='us_saldo_caixa_registro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saldo de Caixa',
                'verbose_name_plural': '2. Saldos de Caixa',
                'ordering': ['-dt_abertura'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(choices=[('ENTRADA_BANCO', 'Entrada do Banco'), ('ENTRADA_RECEBIMENTO', 'Entrada de Recebimento'), ('SAIDA_PAGAMENTO', 'Saída - Pagamento'), ('SAIDA_BANCO', 'Saída para o Banco'), ('SAIDA_OUTRA', 'Saída Outra')], max_length=20, verbose_name='Tipo de Movimentação')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('data_movimentacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Movimentação')),
                ('hora_movimentacao', models.TimeField(auto_now_add=True, verbose_name='Hora da Movimentação')),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Documento')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_cadastros_financeiros.conta', verbose_name='Conta Bancária')),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_caixa', to='admin_pagamentos.pagamento', verbose_name='Pagamento')),
                ('saldo_caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='admin_tesouraria.saldocaixa', verbose_name='Saldo de Caixa')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='us_movimentacao_caixa_atualizacao', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='us_movimentacao_caixa_registro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação de Caixa',
                'verbose_name_plural': '3. Movimentações de Caixa',
                'ordering': ['-data_movimentacao', '-hora_movimentacao'],
            },
        ),
    ]
