# Generated by Django 4.2.20 on 2026-02-28 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProntuarioAcessos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_acesso', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Dt.Acesso')),
                ('motivo_acesso', models.TextField(max_length=255, verbose_name='Motivo de Acesso')),
                ('item_prontuario', models.CharField(blank=True, max_length=255, null=True)),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='atendimentos.atendimento')),
                ('us_acesso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Us.Acesso')),
            ],
            options={
                'verbose_name': 'Log Acessos - Prontuários',
                'verbose_name_plural': '1. Log Acessos - Prontuários',
                'ordering': ['-id'],
            },
        ),
    ]
