# Generated by Django 4.2.20 on 2026-02-28 20:50

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_faturas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appconciliacao', '0001_initial'),
        ('admin_pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaixaFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_baixa', models.CharField(choices=[('PAGAMENTO', 'Pagamento'), ('DEVOLUCAO', 'Devolução'), ('CANCELAMENTO', 'Cancelamento'), ('DESCONTO', 'Desconto'), ('OUTRO', 'Outro')], max_length=20)),
                ('valor_baixa', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_baixa', models.DateField(default=datetime.date.today)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcialmente Baixada'), ('TOTAL', 'Totalmente Baixada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('conciliacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baixas_fatura', to='appconciliacao.conciliacao')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baixas', to='admin_faturas.fatura')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baixas_fatura_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baixas_fatura_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Baixa de Fatura',
                'verbose_name_plural': 'Baixas de Fatura',
                'ordering': ['-data_baixa'],
            },
        ),
        migrations.CreateModel(
            name='BaixaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_baixa', models.CharField(choices=[('RECEBIMENTO', 'Recebimento'), ('DEVOLUCAO', 'Devolução'), ('CANCELAMENTO', 'Cancelamento'), ('DESCONTO', 'Desconto'), ('OUTRO', 'Outro')], max_length=20)),
                ('valor_baixa', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_baixa', models.DateField(default=datetime.date.today)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCILIADO', 'Conciliado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('conciliacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baixas_pagamento', to='appconciliacao.conciliacao')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baixas', to='admin_pagamentos.pagamento')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baixas_pagamento_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baixas_pagamento_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Baixa de Pagamento',
                'verbose_name_plural': 'Baixas de Pagamento',
                'ordering': ['-data_baixa'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioBaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('total_baixas_fatura', models.IntegerField(default=0)),
                ('total_baixas_pagamento', models.IntegerField(default=0)),
                ('valor_total_baixado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado'), ('APROVADO', 'Aprovado')], default='RASCUNHO', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_baixa_atualizados', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_baixa_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório de Baixa',
                'verbose_name_plural': 'Relatórios de Baixa',
                'ordering': ['-data_fim'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoBaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_processo', models.CharField(choices=[('FATURA', 'Fatura'), ('PAGAMENTO', 'Pagamento')], max_length=20)),
                ('status', models.CharField(choices=[('INICIADO', 'Iniciado'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro')], default='INICIADO', max_length=20)),
                ('mensagem_erro', models.TextField(blank=True, null=True)),
                ('total_itens', models.IntegerField(default=0)),
                ('itens_processados', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('baixa_fatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='appbaixa_fatura.baixafatura')),
                ('baixa_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='appbaixa_fatura.baixapagamento')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_baixa_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processo de Baixa',
                'verbose_name_plural': 'Processos de Baixa',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
