# Generated by Django 4.2.20 on 2026-02-28 20:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import dominios.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_cadastros_financeiros', '0001_initial'),
        ('admin_cadastros', '0001_initial'),
        ('admin_financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convenio', models.CharField(help_text='Informe o nome do convênio do contrato', max_length=255, verbose_name='Convênio')),
                ('modalidade_contrato', models.CharField(choices=[('CR', 'Credenciamento'), ('CO', 'Contrato'), ('PA', 'Particular'), ('OU', 'Outro')], max_length=20)),
                ('modo_fatura', models.CharField(choices=[('CL', 'Cliente'), ('CO', 'Convenio')], default='CO', help_text='Escolha se gera uma fatura para todos os clientes ou uma fatura para cada cliente!', max_length=2, verbose_name='Modalidade')),
                ('pre_faturado', models.BooleanField(default=False, verbose_name='Pré-Faturado')),
                ('nr_contrato', models.CharField(max_length=30)),
                ('nr_aditivo', models.CharField(blank=True, max_length=30, null=True)),
                ('inicio_vigencia', models.DateField(help_text='Início vigência do contrato', verbose_name='Início Vigência')),
                ('final_vigencia', models.DateField(help_text='Final vigência do contrato', verbose_name='Final Vigência')),
                ('fatura_vig_inicial', models.BooleanField(default=True, help_text='Marque para gerar pré-fatura no primeiro mês de vigência')),
                ('fatura_vig_final', models.BooleanField(default=True, help_text='Marque para gerar pré-fatura no último mês de vigência')),
                ('dia_envio', models.PositiveSmallIntegerField(default=1, help_text='Dia de envio da fatura', verbose_name='Dia Envio')),
                ('dias_pagamento', models.PositiveSmallIntegerField(default=10, help_text='Dias corridos para pagamento após o envio da fatura/NF', verbose_name='Dias Pagamento')),
                ('valor_mensal', models.DecimalField(blank=True, decimal_places=2, help_text='Valor por cliente', max_digits=10, null=True, verbose_name='Valor Mensal')),
                ('valor_diaria', models.DecimalField(blank=True, decimal_places=2, help_text='Valor por cliente', max_digits=10, null=True, verbose_name='Valor Diária')),
                ('empenho_global', models.CharField(blank=True, help_text='Só marque se o empenho for global e não tiver empenho por cliente. Para empenhos individuais o ajuste deve ser na pré-fatura', max_length=80, null=True)),
                ('tx_retencao_nf', models.DecimalField(blank=True, decimal_places=2, help_text='Informe a taxa de retenção da nota fiscal em percentual', max_digits=5, null=True, verbose_name='Tx.Retenção(%)')),
                ('vl_retencao_nf', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Informe o valor de taxa de retenção', max_digits=10, null=True, verbose_name='Vl.Retenção(R$)')),
                ('descricao_internacao', models.CharField(choices=[('internacao', 'Internação'), ('tratamento', 'Tratamento'), ('acolhimento', 'Acolhimento')], default='tratamento', help_text='Escolha a descrição do tratamento para exibir na descrição da Nota Fiscal', max_length=100)),
                ('descricao_nf', models.CharField(blank=True, help_text='Digite uma descrição padrão para o campo descrição da nota em faturas, ex: Dados Bancários', max_length=256, null=True)),
                ('iniciais_cliente', models.BooleanField(default=True, help_text='Marque para aparecer somente as iniciais do nome do cliente nas descrições de notas')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('cliente', models.ManyToManyField(related_name='clientes_contrato', to='admin_cadastros.pessoa', verbose_name='Cliente(s)')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento', verbose_name='Estabelecimento')),
                ('pagador_pf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagador_pf_contrato', to='admin_cadastros.pessoa', verbose_name='Pagador PF')),
                ('pagador_pj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.empresa', verbose_name='Pagador PJ')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrato_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrato_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Convênio',
                'verbose_name_plural': '1. Convênios',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='PreFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('cliente', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Cliente')),
                ('nr_contrato', models.CharField(blank=True, max_length=100, null=True)),
                ('nr_aditivo', models.CharField(blank=True, max_length=100, null=True)),
                ('empenho', models.CharField(blank=True, max_length=100, null=True)),
                ('dia_envio', models.PositiveSmallIntegerField(default=1, help_text='Dia para enviar o faturamento', verbose_name='Dia Envio')),
                ('dias_pagamento', models.PositiveSmallIntegerField(default=10, help_text='Dias corridos para pagamento após o envio da fatura/NF', verbose_name='Dias corridos para pagamento')),
                ('competencia', models.DateField(verbose_name='Competência')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da pré-fatura bruto, sem taxas e retenções', max_digits=10, verbose_name='Valor Bruto')),
                ('pre_faturado', models.BooleanField(default=False)),
                ('dt_vencimento', models.DateField(help_text='Vencimento da Fatura', verbose_name='Vencimento')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prefaturas', to='admin_faturas.convenio', verbose_name='Convênio')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento', verbose_name='Estabelecimento')),
                ('pagador_pf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagador_pf', to='admin_cadastros.pessoa', verbose_name='Pagador Pessoa Física')),
                ('pagador_pj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.empresa', verbose_name='Pagador Pessoa Jurídica')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_fatura_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_fatura_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Pré-Fatura',
                'verbose_name_plural': '2. Pré-Faturas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('prefatura_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_faturas.prefatura')),
                ('tx_retencao_nf', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taxa Retenção(%)')),
                ('valor_fatura', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Fatura')),
                ('valor_saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Saldo')),
                ('dt_liquidacao', models.DateField(blank=True, null=True, verbose_name='Data Liquidação')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('nr_nota_fiscal', models.CharField(blank=True, help_text='Nota Fiscal', max_length=50, null=True, verbose_name='NF')),
                ('periodo_tratamento', models.CharField(blank=True, help_text='Período de Tratamento', max_length=255, null=True, verbose_name='Período')),
                ('faturado', models.BooleanField(default=False, verbose_name='Faturado')),
                ('anexo_nf', models.FileField(blank=True, help_text='Adicione arquivos dos formatos PDF, JPG, JPEG, PNG.', null=True, upload_to='anexos/nf/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), dominios.utils.validate_anexo_file], verbose_name='Anexo NF')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': '3. Faturas',
                'ordering': ['-id'],
            },
            bases=('admin_faturas.prefatura',),
        ),
        migrations.CreateModel(
            name='BaixaFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_baixa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dt_recebimento', models.DateField()),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('competencia_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_financeiro.competenciabancaria')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estab_baixa_fatura', to='admin_cadastros.estabelecimento')),
                ('transacao_financeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros_financeiros.transacaofinanceira')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baixa_fat_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baixa_fat_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_faturas.fatura')),
            ],
            options={
                'verbose_name': 'Baixa de Fatura',
                'verbose_name_plural': '4. Baixa de Faturas',
                'ordering': ['-dt_recebimento'],
            },
        ),
    ]
