# Generated by Django 4.2.20 on 2026-02-28 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_agencia', models.CharField(max_length=10)),
                ('descricao_agencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Agência',
                'verbose_name_plural': '2. Agências',
            },
        ),
        migrations.CreateModel(
            name='TransacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transacao_financeira', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('nenhum', 'Não Movimenta')], max_length=7)),
                ('movimento', models.CharField(choices=[('caixa', 'Movimenta Caixa'), ('banco', 'Movimenta Banco'), ('nenhum', 'Não Movimenta')], max_length=7)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('estabelecimento', models.ForeignKey(help_text='Estabelecimento associado a esta transação', on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento')),
            ],
            options={
                'verbose_name': 'Transação Financeira',
                'verbose_name_plural': '7. Transações Financeiras',
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_conta', models.CharField(help_text='Informe com o digito e sem caracteres especiais', max_length=20)),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('padrao', models.BooleanField(blank=True, default=False, help_text='Movimentação financeira padrão do estabelecimento', null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='admin_cadastros_financeiros.agencia')),
                ('estabelecimento', models.ForeignKey(help_text='Estabelecimento associado a esta conta', on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': '3. Contas',
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_banco', models.CharField(max_length=10, unique=True)),
                ('descricao_banco', models.CharField(max_length=100)),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('estabelecimento', models.ForeignKey(help_text='Estabelecimento associado a este banco', on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': '1. Bancos',
            },
        ),
        migrations.AddField(
            model_name='agencia',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agencias', to='admin_cadastros_financeiros.banco'),
        ),
        migrations.AddField(
            model_name='agencia',
            name='estabelecimento',
            field=models.ForeignKey(help_text='Estabelecimento associado a esta agência', on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento'),
        ),
    ]
