# Generated by Django 4.2.20 on 2026-02-28 20:50

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_admissao', models.DateField(default=datetime.date.today, verbose_name='Data de Admissão')),
                ('dt_desligamento', models.DateField(blank=True, null=True, verbose_name='Data de Desligamento')),
                ('senha_alterada', models.BooleanField(default=False)),
                ('certificado_digital', models.FileField(blank=True, null=True, upload_to='certificados/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pfx'])])),
                ('validade_certificado', models.DateField(blank=True, null=True, verbose_name='Validade do Certificado')),
                ('senha_certificado', models.CharField(blank=True, max_length=255, null=True, verbose_name='Senha do Certificado')),
                ('estabelecimento', models.ManyToManyField(to='admin_cadastros.estabelecimento')),
                ('estabelecimento_padrao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfis_padrao', to='admin_cadastros.estabelecimento', verbose_name='Estabelecimento Padrão')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_cadastros.pessoa', verbose_name='Funcionario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
