# Generated by Django 4.2.20 on 2026-02-28 20:50

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_cadastros_financeiros', '0001_initial'),
        ('admin_cadastros', '0001_initial'),
        ('admin_financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conciliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_conciliado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Conciliado')),
                ('diferenca', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Diferença')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Conciliado'), ('D', 'Divergente'), ('A', 'Anulado')], default='P', max_length=1, verbose_name='Status da Conciliação')),
                ('motivo_divergencia', models.TextField(blank=True, null=True, verbose_name='Motivo da Divergência')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True)),
                ('competencia_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_financeiro.competenciabancaria', verbose_name='Competência Bancária')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento')),
                ('movimento_bancario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_financeiro.movimentobancario', verbose_name='Movimento Bancário')),
            ],
            options={
                'verbose_name': 'Conciliação',
                'verbose_name_plural': '3. Conciliações',
                'ordering': ['-dt_registro'],
            },
        ),
        migrations.CreateModel(
            name='ExtratoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='extratos_bancarios/', verbose_name='Arquivo do Extrato')),
                ('tipo_arquivo', models.CharField(choices=[('CSV', 'CSV'), ('OFX', 'OFX'), ('MANUAL', 'Manual')], default='CSV', max_length=10, verbose_name='Tipo de Arquivo')),
                ('data_extrato_inicio', models.DateField(verbose_name='Data Início do Extrato')),
                ('data_extrato_fim', models.DateField(verbose_name='Data Fim do Extrato')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Inicial do Extrato')),
                ('saldo_final', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Final do Extrato')),
                ('total_entradas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total de Entradas')),
                ('total_saidas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total de Saídas')),
                ('quantidade_transacoes', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Transações')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('competencia_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_financeiro.competenciabancaria', verbose_name='Competência Bancária')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros_financeiros.conta', verbose_name='Conta Bancária')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='us_extrato_atualizacao', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='us_extrato_registro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extrato Bancário',
                'verbose_name_plural': '1. Extratos Bancários',
                'ordering': ['-dt_registro'],
            },
        ),
        migrations.CreateModel(
            name='TransacaoExtrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_transacao', models.DateField(verbose_name='Data da Transação')),
                ('data_lancamento', models.DateField(blank=True, null=True, verbose_name='Data de Lançamento')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('tipo_transacao', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1, verbose_name='Tipo de Transação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Documento')),
                ('referencia_banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referência do Banco')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('conciliada', models.BooleanField(default=False, verbose_name='Conciliada?')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('extrato_bancario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='admin_conciliacao.extratobancario', verbose_name='Extrato Bancário')),
            ],
            options={
                'verbose_name': 'Transação do Extrato',
                'verbose_name_plural': '2. Transações do Extrato',
                'ordering': ['data_transacao', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DivergenciaConciliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_divergencia', models.CharField(choices=[('VALOR', 'Diferença de Valor'), ('DATA', 'Diferença de Data'), ('FALTANTE', 'Transação Faltante no Sistema'), ('EXCEDENTE', 'Transação Excedente no Sistema'), ('DUPLICADA', 'Transação Duplicada'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo de Divergência')),
                ('descricao', models.TextField(verbose_name='Descrição da Divergência')),
                ('prioridade', models.CharField(choices=[('A', 'Alta'), ('M', 'Média'), ('B', 'Baixa')], default='M', max_length=1, verbose_name='Prioridade')),
                ('resolvida', models.BooleanField(default=False, verbose_name='Resolvida?')),
                ('solucao', models.TextField(blank=True, null=True, verbose_name='Solução Aplicada')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dt_resolucao', models.DateTimeField(blank=True, null=True)),
                ('conciliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divergencias', to='admin_conciliacao.conciliacao', verbose_name='Conciliação')),
                ('us_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='us_divergencia_registro', to=settings.AUTH_USER_MODEL)),
                ('us_resolucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='us_divergencia_resolucao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Divergência de Conciliação',
                'verbose_name_plural': '4. Divergências de Conciliação',
                'ordering': ['-prioridade', '-dt_registro'],
            },
        ),
        migrations.AddField(
            model_name='conciliacao',
            name='transacao_extrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_conciliacao.transacaoextrato', verbose_name='Transação do Extrato'),
        ),
        migrations.AddField(
            model_name='conciliacao',
            name='us_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='us_conciliacao_atualizacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conciliacao',
            name='us_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='us_conciliacao_registro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transacaoextrato',
            index=models.Index(fields=['extrato_bancario', 'conciliada'], name='admin_conci_extrato_21808f_idx'),
        ),
        migrations.AddIndex(
            model_name='transacaoextrato',
            index=models.Index(fields=['data_transacao'], name='admin_conci_data_tr_7c22cc_idx'),
        ),
        migrations.AddIndex(
            model_name='conciliacao',
            index=models.Index(fields=['status', 'competencia_bancaria'], name='admin_conci_status_2ef68f_idx'),
        ),
        migrations.AddIndex(
            model_name='conciliacao',
            index=models.Index(fields=['transacao_extrato'], name='admin_conci_transac_bfa54f_idx'),
        ),
        migrations.AddIndex(
            model_name='conciliacao',
            index=models.Index(fields=['movimento_bancario'], name='admin_conci_movimen_43da6c_idx'),
        ),
    ]
