# Generated by Django 4.2.20 on 2026-02-28 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_cadastros_financeiros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenciaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Utilize uma descrição, como exemplo = JANEIRO/2024', max_length=100)),
                ('dt_abertura_competencia', models.DateField()),
                ('dt_fechamento_competencia', models.DateField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_atual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Competência Bancária',
                'verbose_name_plural': '2. Competências Bancárias',
            },
        ),
        migrations.CreateModel(
            name='MovimentoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor E')),
                ('valor_saida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor S')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('competencia_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_financeiro.competenciabancaria', verbose_name='Competência (Aberta)')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento')),
                ('transacao_financeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros_financeiros.transacaofinanceira', verbose_name='Transação Financeira')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimento_atualizacao', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimento_registro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimento Bancário',
                'verbose_name_plural': '3. Movimentos Bancários',
            },
        ),
        migrations.CreateModel(
            name='ControleBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros_financeiros.conta')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uscontbanc_atualizacao', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uscontbanc_registro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Controle Bancário',
                'verbose_name_plural': '1. Controles Bancários',
            },
        ),
        migrations.AddField(
            model_name='competenciabancaria',
            name='controle_bancario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_financeiro.controlebancario'),
        ),
        migrations.AddField(
            model_name='competenciabancaria',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento'),
        ),
        migrations.AddField(
            model_name='competenciabancaria',
            name='us_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ussaldo_atualizacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competenciabancaria',
            name='us_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ussaldo_registro', to=settings.AUTH_USER_MODEL),
        ),
    ]
