# Generated by Django 4.2.20 on 2026-02-28 20:50

import django.contrib.sessions.models
from django.db import migrations, models
import dominios.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', max_length=255)),
                ('email_host', models.CharField(default='smtp.zoho.com', max_length=255)),
                ('email_port', models.PositiveIntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.EmailField(default='nao-responda@managerontecsolutions.com.br', max_length=254)),
                ('email_host_password', dominios.utils.EncryptedCharField(help_text='Senha do e-mail remetente, sempre que editar esta tabela, precisara repassar novamente a senha do e-mail', max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('valid_days', models.PositiveIntegerField()),
                ('regra', models.CharField(choices=[('redefinicao de senha', 'redefinicao de senha'), ('financeiro', 'financeiro'), ('nota fiscal', 'nota fiscal')], max_length=255)),
            ],
            options={
                'verbose_name': 'E-mail e configuração',
                'verbose_name_plural': '1. E-mails e configurações',
            },
        ),
        migrations.CreateModel(
            name='QtdUsuariosSimultaneos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_usuarios_simultaneos', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Quantidade de Usuários Simultâneos',
                'verbose_name_plural': '2. Quantidade de Usuários Simultâneos',
            },
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
            ],
            options={
                'verbose_name': 'Usuário Logado',
                'verbose_name_plural': 'Usuários Logados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sessions.session',),
            managers=[
                ('objects', django.contrib.sessions.models.SessionManager()),
            ],
        ),
    ]
