# Generated by Django 4.2.20 on 2026-02-28 20:50

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('numero_caixa', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Tesouraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('numero_tesouraria', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tesourarias', to='admin_cadastros.estabelecimento')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tesourarias_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tesourarias_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tesouraria',
                'verbose_name_plural': 'Tesourarias',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SaldoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateField(default=datetime.date.today)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado')], default='A', max_length=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='apptesouraria.caixa')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldos_caixa_atualizados', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldos_caixa_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saldo de Caixa',
                'verbose_name_plural': 'Saldos de Caixa',
                'ordering': ['-data_abertura'],
                'unique_together': {('caixa', 'data_abertura')},
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('origem', models.CharField(choices=[('BANCO', 'Banco'), ('RECEBIMENTO', 'Recebimento'), ('PAGAMENTO', 'Pagamento'), ('SAQUE', 'Saque'), ('OUTRA', 'Outra')], max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('C', 'Cancelado')], default='A', max_length=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('saldo_caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='apptesouraria.saldocaixa')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_caixa_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_caixa_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação de Caixa',
                'verbose_name_plural': 'Movimentações de Caixa',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='caixa',
            name='tesouraria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caixas', to='apptesouraria.tesouraria'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='us_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixas_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caixa',
            name='us_registro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixas_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='caixa',
            unique_together={('tesouraria', 'numero_caixa')},
        ),
    ]
