# Generated by Django 4.2.20 on 2026-02-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao_sessao', models.IntegerField(default=36000, help_text='Defina em micro segundos o tempo de duração de sessão, após este tempo o usuário perde a autenticação no sistema, ex: 36000 = 1 hora')),
            ],
            options={
                'verbose_name': 'Configuração de Sessão',
                'verbose_name_plural': '1. Configurações de Sessão',
            },
        ),
    ]
