# Generated by Django 4.2.20 on 2026-02-28 20:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=255, unique=True)),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': '4. Cidades',
                'ordering': ['cidade'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidade', models.CharField(choices=[('b', 'Brasileira'), ('e', 'Estrangeira')], default='b', max_length=255, verbose_name='Nacionalidade')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('fantasia', models.CharField(default='', max_length=255, verbose_name='Nome de Fantasia')),
                ('empresa', models.CharField(default='', max_length=255, verbose_name='Empresa Apelido')),
                ('cnpj', models.CharField(blank=True, default='', max_length=14, null=True, unique=True, verbose_name='CNPJ')),
                ('nome_responsavel', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nome do Responável')),
                ('nome_contato', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nome do Contato')),
                ('whats', models.CharField(blank=True, default='', max_length=14, null=True)),
                ('telefone', models.CharField(blank=True, default='', max_length=14, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=50, null=True, verbose_name='E-mail')),
                ('rua', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Rua')),
                ('numero', models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('bairro', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('cep', models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='CEP')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('cidade', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.cidade', verbose_name='cidade')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': '8. Empresas',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2, unique=True, verbose_name='UF')),
                ('estado', models.CharField(max_length=255, unique=True)),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estado_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estado_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': '3. Estados',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': '6. Gêneros',
                'ordering': ['genero'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=255, unique=True, verbose_name='País')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pais_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pais_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': '5. Países',
                'ordering': ['pais'],
            },
        ),
        migrations.CreateModel(
            name='TipoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atendimento', models.CharField(max_length=30, verbose_name='Tipos de Atendimentos')),
                ('observacoes', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Observações')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipo_atendimento_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipo_atendimento_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Tipo de Atendimento',
                'verbose_name_plural': '10. Tipos de Atendimentos',
                'ordering': ['tipo_atendimento'],
            },
        ),
        migrations.CreateModel(
            name='PessoaCampos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(choices=[('pais', 'pais'), ('dt_nascimento', 'dt_nascimento'), ('alergias', 'alergias'), ('cpf', 'cpf'), ('rg', 'rg'), ('genero', 'genero'), ('whats', 'whats'), ('estado_civil', 'estado_civil'), ('telefone', 'telefone'), ('email', 'email'), ('responsavel', 'responsavel'), ('mae', 'mae'), ('pai', 'pai'), ('cor_raca', 'cor_raca'), ('religiao', 'religiao'), ('cep', 'cep'), ('rua', 'rua'), ('numero', 'numero'), ('bairro', 'bairro'), ('complemento', 'complemento'), ('estado', 'estado'), ('cidade', 'cidade'), ('naturalidade', 'naturalidade')], help_text='Definição de Campos obrigatórios para Cadastro de Pessoas', max_length=100)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pessoa_campos_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pessoa_campos_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Pessoa - campo obrigatório',
                'verbose_name_plural': '2. Pessoas - campos obrigatórios',
                'ordering': ['campo'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('classificacao_pessoa', models.CharField(choices=[('paciente', 'Paciente'), ('funcionario', 'Funcionário')], max_length=15, verbose_name='Classificação')),
                ('nacionalidade', models.CharField(choices=[('b', 'Brasileira'), ('e', 'Estrangeira')], default='b', max_length=255)),
                ('dt_nascimento', models.DateField(blank=True, default='', null=True, verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('f', 'Feminino'), ('m', 'Masculino')], max_length=1)),
                ('alergico', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, verbose_name='Alérgico?')),
                ('alergias', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Descrição de Alergias')),
                ('cpf', models.CharField(blank=True, default='', max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, default='', max_length=11, null=True, unique=True, verbose_name='RG')),
                ('estado_civil', models.CharField(blank=True, choices=[('C', 'Casado'), ('S', 'Solteiro'), ('D', 'Divorciado'), ('V', 'Viúvo')], max_length=15, null=True, verbose_name='Estado Civil')),
                ('cor_raca', models.CharField(blank=True, choices=[('branco', 'Branco'), ('preto', 'Preto'), ('pardo', 'Pardo'), ('amarelo', 'Amarelo'), ('indigena', 'Indigena')], max_length=20, null=True, verbose_name='Cor/Raça')),
                ('religiao', models.CharField(blank=True, choices=[('cristianismo', 'Cristianismo'), ('catolico', 'Católico'), ('evangelico', 'Evangélico'), ('luterano', 'Luterano'), ('testemunha_jeova', 'Testemunha de Jeová'), ('budismo', 'Budismo'), ('hinduismo', 'Hinduísmo'), ('islamismo', 'Islamismo'), ('judaismo', 'Judaísmo'), ('siquismo', 'Siquismo'), ('taoismo', 'Taoísmo'), ('ateismo', 'Ateísmo'), ('agnosticismo', 'Agnosticismo')], max_length=20, null=True, verbose_name='Religião')),
                ('whats', models.CharField(blank=True, default='', max_length=14, null=True)),
                ('telefone', models.CharField(blank=True, default='', max_length=14, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=255, null=True, verbose_name='E-mail')),
                ('mae', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nome da Mãe')),
                ('pai', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nome do Pai')),
                ('cep', models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='CEP')),
                ('rua', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Rua/Avenida')),
                ('numero', models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('bairro', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('cidade', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.cidade', verbose_name='cidade')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estado_pessoa', to='admin_cadastros.estado', verbose_name='estado')),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.genero')),
                ('naturalidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='naturalidade_pessoa', to='admin_cadastros.cidade')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.pais', verbose_name='País')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsavel_pessoa', to='admin_cadastros.pessoa', verbose_name='Nome do Responsável')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pessoa_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pessoa_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': '7. Pessoas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estabelecimento', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('M', 'Matriz'), ('F', 'Filial'), ('O', 'Outras')], max_length=50)),
                ('logo', models.ImageField(blank=True, help_text='Adicione arquivos dos formatos JPG, JPEG, PNG.', null=True, upload_to='anexos/logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Logotipos')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.empresa')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estabelecimento_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estabelecimento_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Estabelecimento',
                'verbose_name_plural': '9. Estabelecimentos',
                'ordering': ['estabelecimento'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaCampos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(choices=[('nome_responsavel', 'nome_responsavel'), ('empresa', 'empresa'), ('cnpj', 'cnpj'), ('nome_contato', 'nome_contato'), ('whats', 'whats'), ('telefone', 'telefone'), ('email', 'email'), ('rua', 'rua'), ('numero', 'numero'), ('bairro', 'bairro'), ('cep', 'cep'), ('estado', 'estado'), ('cidade', 'cidade')], help_text='Definição de Campos obrigatórios para Cadastro de Empresas', max_length=100)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa_campos_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa_campos_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Empresa - campo obrigatório',
                'verbose_name_plural': '1. Empresas - campos obrigatórios',
                'ordering': ['campo'],
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estado', verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='us_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='us_registro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estado'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='us_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cidade_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='us_registro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cidade_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro'),
        ),
        migrations.AddConstraint(
            model_name='tipoatendimento',
            constraint=models.UniqueConstraint(fields=('tipo_atendimento', 'status'), name='unique_tipo_atendimento_status'),
        ),
        migrations.AlterUniqueTogether(
            name='pessoacampos',
            unique_together={('campo',)},
        ),
        migrations.AddConstraint(
            model_name='pais',
            constraint=models.UniqueConstraint(fields=('pais', 'status'), name='unique_pais_status'),
        ),
        migrations.AddConstraint(
            model_name='estado',
            constraint=models.UniqueConstraint(fields=('uf', 'status'), name='unique_estado_status'),
        ),
        migrations.AddConstraint(
            model_name='estabelecimento',
            constraint=models.UniqueConstraint(fields=('estabelecimento', 'status'), name='unique_estabelecimento_status'),
        ),
        migrations.AlterUniqueTogether(
            name='empresacampos',
            unique_together={('campo',)},
        ),
        migrations.AddConstraint(
            model_name='empresa',
            constraint=models.UniqueConstraint(fields=('cnpj', 'status'), name='unique_empresa_status'),
        ),
        migrations.AddConstraint(
            model_name='cidade',
            constraint=models.UniqueConstraint(fields=('cidade', 'status'), name='unique_cidade_status'),
        ),
    ]
