# Generated by Django 4.2.20 on 2026-02-28 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_cadastros_assistenciais', '0001_initial'),
        ('admin_cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosPrescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.PositiveIntegerField(choices=[(1, 'Mesmo dia'), (2, '2 dias'), (3, '3 dias'), (4, '4 dias'), (5, '5 dias'), (6, '6 dias'), (7, '7 dias'), (8, '8 dias'), (9, '9 dias'), (10, '10 dias'), (11, '11 dias'), (12, '12 dias'), (13, '13 dias'), (14, '14 dias'), (15, '15 dias'), (16, '15 dias'), (17, '17 dias'), (18, '18 dias'), (19, '19 dias'), (20, '20 dias'), (21, '21 dias'), (22, '22 dias'), (23, '23 dias'), (24, '24 dias'), (25, '25 dias'), (26, '26 dias'), (27, '27 dias'), (28, '28 dias'), (29, '29 dias'), (30, '30 dias')], default='1', help_text='Validade de dias posteriores a data inicial, para permitir prescrever', verbose_name='Intervalo Dias Permitido')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('permite_prescricao_retroativa', models.BooleanField(default=False, help_text='NÃO RECOMENDADO! Permissão para prescrever retroativamente, utilizado em implantações/exceções!')),
                ('permite_editar_outras', models.BooleanField(default=False, help_text='Permissão para editar prescrições de outros profissionais')),
                ('permite_suspender_outras', models.BooleanField(default=False, help_text='Permissão para suspender prescrições de outros profissionais')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento', verbose_name='Estabelecimento')),
                ('profissao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros_assistenciais.profissao', verbose_name='Profissão Prescrição')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profissional_prescricao', to=settings.AUTH_USER_MODEL, verbose_name='Profissional Prescrição')),
            ],
            options={
                'verbose_name': 'Parametros Prescrição',
                'verbose_name_plural': '1. Parametros Prescricao',
            },
        ),
        migrations.CreateModel(
            name='IntervaloHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('intervalo_horas', models.PositiveIntegerField(choices=[(1, '1/1 h'), (2, '2/2 h'), (3, '3/3 h'), (4, '4/4 h'), (5, '5/5 h'), (6, '6/6 h'), (7, '7/7 h'), (8, '8/8 h'), (9, '9/9 h'), (10, '10/10 h'), (11, '11/11 h'), (12, '12/12 h'), (24, '24/24 h')], verbose_name='Intervalo em horas')),
                ('padrao', models.BooleanField(default=False)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento', verbose_name='Estabelecimento')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_registro', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Intervalo em horas para prescrições',
                'verbose_name_plural': '2. Intervalos em horas para prescrições',
                'ordering': ['-pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InicioPlanoTerapeutico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('hora_inicio', models.TimeField(default='07:00:00', verbose_name='Hora inicial do plano terapêutico')),
                ('padrao', models.BooleanField(default=False)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento', verbose_name='Estabelecimento')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_registro', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Horário padrão para início do plano terapêutico prescrito',
                'verbose_name_plural': '3. Horário padrão para início do plano terapêutico prescrito',
                'ordering': ['-pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HorarioRestritoPrescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('hora_inicio', models.TimeField(default='00:00:00', verbose_name='Hora inicial de restrição')),
                ('hora_final', models.TimeField(default='06:00:00', verbose_name='Hora final de restrição')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento', verbose_name='Estabelecimento')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_registro', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Horário Restrito para prescrição',
                'verbose_name_plural': '4. Horários Restritos para prescrições',
                'ordering': ['-pk'],
                'abstract': False,
            },
        ),
    ]
