# Generated by Django 4.2.20 on 2026-02-28 20:50

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_faturas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_cadastros', '0001_initial'),
        ('admin_pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtratoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_banco', models.CharField(max_length=10)),
                ('numero_agencia', models.CharField(max_length=10)),
                ('numero_conta', models.CharField(max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_final', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tipo_arquivo', models.CharField(choices=[('CSV', 'CSV'), ('XLS', 'XLS'), ('PDF', 'PDF')], max_length=10)),
                ('arquivo', models.FileField(upload_to='extratos_bancarios/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCILIADO', 'Conciliado'), ('PARCIAL', 'Parcialmente Conciliado')], default='PENDENTE', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extratos_bancarios', to='admin_cadastros.estabelecimento')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extratos_bancarios_atualizados', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extratos_bancarios_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extrato Bancário',
                'verbose_name_plural': 'Extratos Bancários',
                'ordering': ['-data_fim'],
                'unique_together': {('numero_banco', 'numero_agencia', 'numero_conta', 'data_inicio', 'data_fim')},
            },
        ),
        migrations.CreateModel(
            name='RelatorioConciliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('total_lancamentos', models.IntegerField(default=0)),
                ('total_conciliado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_pendente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado'), ('APROVADO', 'Aprovado')], default='RASCUNHO', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_conciliacao', to='admin_cadastros.estabelecimento')),
                ('extrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='appconciliacao.extratobancario')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_conciliacao_atualizados', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_conciliacao_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório de Conciliação',
                'verbose_name_plural': 'Relatórios de Conciliação',
                'ordering': ['-data_fim'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lancamento', models.DateField()),
                ('tipo', models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descricao', models.CharField(max_length=255)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('extrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='appconciliacao.extratobancario')),
            ],
            options={
                'verbose_name': 'Lançamento Bancário',
                'verbose_name_plural': 'Lançamentos Bancários',
                'ordering': ['-data_lancamento'],
            },
        ),
        migrations.CreateModel(
            name='Conciliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transacao', models.CharField(choices=[('FATURA', 'Fatura'), ('PAGAMENTO', 'Pagamento'), ('MOVIMENTACAO_CAIXA', 'Movimentação de Caixa')], max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCILIADO', 'Conciliado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('fatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliacoes', to='admin_faturas.fatura')),
                ('lancamento_bancario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliacoes', to='appconciliacao.lancamentobancario')),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliacoes', to='admin_pagamentos.pagamento')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliacoes_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliacoes_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conciliação',
                'verbose_name_plural': 'Conciliações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
