# Generated by Django 4.2.20 on 2026-10-08 15:05

import django.core.validators
from django.db import migrations, models
import documentos_legais.models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos_legais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentolegalinternacao',
            name='foto_documento',
            field=models.ImageField(blank=True, help_text='Foto do documento de identificação do responsável, capturada junto da selfie.', null=True, upload_to=documentos_legais.models.foto_documento_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Foto do Documento'),
        ),
        migrations.AddField(
            model_name='modelodocumentolegal',
            name='exige_assinatura_atendente',
            field=models.BooleanField(default=True, help_text='Quando marcado, habilita a assinatura digital por certificado do funcionário logado.', verbose_name='Exige assinatura do atendente'),
        ),
        migrations.AddField(
            model_name='modelodocumentolegal',
            name='exige_assinatura_responsavel',
            field=models.BooleanField(default=True, help_text='Quando marcado, o termo exige a assinatura desenhada e as fotos do responsável e do documento.', verbose_name='Exige assinatura do responsável'),
        ),
        migrations.AlterField(
            model_name='documentolegalinternacao',
            name='declaracao_aceite',
            field=models.BooleanField(default=True, verbose_name='Li e concordo com o termo'),
        ),
    ]
