# Generated by Django 4.2.20 on 2026-10-08 17:41

import django.core.validators
from django.db import migrations, models
import documentos_legais.models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos_legais', '0002_documentolegalinternacao_foto_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentolegalinternacao',
            name='documento_frente',
        ),
        migrations.RemoveField(
            model_name='documentolegalinternacao',
            name='documento_verso',
        ),
        migrations.AlterField(
            model_name='documentolegalinternacao',
            name='selfie',
            field=models.ImageField(blank=True, help_text='Foto (selfie) do responsável capturada na validação.', null=True, upload_to=documentos_legais.models.selfie_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Foto do Responsável'),
        ),
    ]
