# Generated by Django 4.2.20 on 2026-10-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos_legais', '0003_remove_documentolegalinternacao_documento_frente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentolegalinternacao',
            name='responsavel_cpf',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF do Responsável'),
        ),
        migrations.AlterField(
            model_name='documentolegalinternacao',
            name='responsavel_data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento do Responsável'),
        ),
        migrations.AlterField(
            model_name='documentolegalinternacao',
            name='responsavel_documento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento de Identificação'),
        ),
        migrations.AlterField(
            model_name='documentolegalinternacao',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável'),
        ),
    ]
