BBBB BBBBBB
BBBB BB

XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXX
  XXXXXX
    XXXXXXX
      BBBBB BBBBBBB

      BBBBBBBBXXXXXXXXXXXX
    XXXXXXXX

    XXXXXXX
      XXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XX XXX XXXXXXXX XXXXXX XX XXXXXXXXX XX
        XXXXXX XXXXXXX XXXXXXXXXXX XX XXX XX XXXXX XXXXXXX XX
      X
      
      XXXXXXXXXX X
        XXXXXX XXXX
      X
      
      XXXXXXXXXX XXXXXX
      XXXXXXXXXX XXXXXX X
        XXXXXX XXXX
      X
      
      XXXXXXXXXX X
        XXXXXXX XXXXX
        XXXXXX XXXXXX
        XXXXXXXXX XXXXXX
        XXXX XX
        XXXXXXXX XXXXX
      X
      
      XXXXXXXX X
        XXXXXXXXX XXXXXX
        XXXX XX
        XXXXXX XXXXX
        XXXXXXX XXXXX
        XXXXXXXX XXXXX
      X
      
      XXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXX XXXX XX XXXXXX XXXX XXXXX XXXX X XXXXXX XX XXX XXXXXX XX
        XXXXXXX XXXXXXXXXX X XXXXXX
      X
      
      XXXXXXXXXX X
        XXXXXX XXXXXX XX XXXXXX XXXX X XXXXXXX XXXXXXXX XX
        XXXXXXXXX XXXXXX
        XXXXXXX XXXXXX
        XXXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXX
      X
      
      XXXXXXXXXXXXXX X
        XXXXXXXXX XXXXXX XX XXXXXXXXX XX
        XXXX XXXXX XX XXXXXX XX XXXXXXXXX XX
        XX XXXXXXX XX XXXXXXXXX XX
        XXXXXXXXXXXX XXXXXX XX XXXXXX X XXXXXX XXXXXXXX XX
        XXXXXXXXX XXXXX XX XXXXXXXX XXXXXXX XX XXXXXXXX XX
        XXXXXX XXXXXXXXX X XXXXXXX XX XXX XX
        XXXXXXX XXXXX
      X
      
      XXXXXXXXX X
        XXXXXXXXX XXXXXXX
        XXXX XX
        XXXXXXXX XXX
      X
      
      XXXXXXXXXXXXXXXX X
        XXXXXXXXX XXXXXXXXX XX XXXXXXX XXX X XXXXX XXXXX XXXX XX XXXXXXX X XXXX XXXXXXXXX XX
        XX XXXXXXXXX XXXXX XXXX XXXXXX XXXXXXXXX XX XXXXX XX XXXXXX XXXXXXXXX XX XXXXXX XX
        XXXXXXXXXXX XXXXX
        XXXXXXX XXXXXXXXXX X XXXXXXX XXXXXXX
        XXXXXXXX XXX
      X
      
      XXXXXXXXXXXXXXXXX X
        XXXXXX XXXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
      X
      
      XXXXXXXXX X
        XXXXXXX XXXXX
        XXXXXXXXX XXXXXX
        XXXXXXX XX
        XXXXXX XXXXXXXXX XXXXXXXX
        XXXXXXXX XXXX
      X
      
      XXXXX X
        XXXXXX XXXXX
      X
      
      XXXXX X
        XXXXXXXXX XXXXXXX
        XXXX XX
        XXXXXXXX XXX
      X
      
      XXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXX XXXXXXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXX
        XXXXXXX XXX XXXXX XXXXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXXX X X XXX XXXXXXX XX XX XXXXX
      X
      
      XXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXX XXXXX
        XXXXXXXX XX
        XXXXXXX XX
        XXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXX
        XXXXXXX XXX XXXXX XXXXXXXX
      X
      
      XXXXXXXXXXXXX XX X
        XXXXXXXX XXX XXXXX
        XXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXX XXXXXX
        XXXXXXXXXX XXXXXXXXXXX
      X
      
      XXXXXXXXXXXXX XXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX
      X
      
      XXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXX XXXXXXXXX
        XXXXX XXXXX
        XXXX XX
        XXXXXXXXXXXX XXXXXXX
        XXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXX XXX XXXXX XXXXXXXX
      X
      
      XXXXXXXXXXXXXXXXXX XXXXXXXX X
        XXXXXXXX XXXXXX
      X
      
      XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXX XXXXXXXXX
        XXXXXX XXXXX
      X
      
      XXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXX
        XXXXXX XXXXXX
        XXXXXXXX XXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXXXXXXXXXX
      X
      
      XXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
      X
    XXXXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBB
  XXXXXXX

  XXXXX XXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBB
    BBBBB

    XXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXX XXXXXXXXX
          XXXXX
            XX XXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXX 
          XXXXXX
          XXX XX

          BB BBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXX
              XX XXXXXXXXXX XXXXXXXXXXXXXXXXX 
            XXXXXX
            XXX XX
          BBBBB
        XXXXXX
        BBBBB BBBBB

        BBBBBBBB
      XXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXX XXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              BBBBB BBBBBBBB

              BBBBBBBB
            XXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
          BB BBBBBBBB
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
              XXXXXX
            XXXXXX
          BBBBB

          BBBBB BBBBB

          BBBBBBBB
        XXXXXX

        BB BBBBBBBBBBBB
          XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
            BBBBB BBBBBBBB

            BBBBBBBB
          XXXXXX
        BBBBB
      XXXXXXX
    XXXXXXXXXX

    BBBBB BBBBBBBBBBBB

    BBBBBBBB

    XXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX X
        XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      
        XXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
      
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
          XXXXXXXXXXXX
        XX
      
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXX X
            XXXXXXXXXXXX
          X
        XX
      
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXX X
            XXXXXXXXXXXXXX
          X
        XX
      
        XXXXXXXX XXXXXXXXXXXX X
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX X
            XXXXXXXXXXXXXX
          X XXXX X
            XXXXXXXXXXXX
          X
        X
      
        XXXXXXXX XXXXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        X
      
        XXXXXXXX XXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
        X
      
        XXXXXXXX XXXXXXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXX X XXXXX
          XXXXXXXXXXXXXXXXXXXX X XXXXX
          XXXXXXXXXXXXXXXXXXXXXXX X XXXXX
          XXXXXXXXXXXXXXXXXX X XXXXXXXXXX X XXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX
          XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX X XXXXXXXXXX
        X
      XX
    XXXXXXXXX
  XXXXXXX
XXXXXXX
