BBBB BBBBBB
BBBB BB

XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXX
  XXXXXX
    XXXXXXX
      BBBBB BBBBBBB

      BBBBBBBBXXXXXXXXXXXX
    XXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBB
  XXXXXXX
  XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBBBB BBBBBBB

      BBBBBBBB
      BBBBB BBBBBBBBBBBB

      BBBBBBBB
    XXXXXX
  XXXXXXX
XXXXXXX
