# Generated by Django 4.2.20 on 2026-02-28 20:50

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito')], max_length=10)),
                ('numero_cartao', models.CharField(max_length=20, unique=True)),
                ('bandeira', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('ELO', 'Elo'), ('AMEX', 'American Express'), ('DINERS', 'Diners'), ('OUTRA', 'Outra')], max_length=20)),
                ('limite', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('dia_fechamento', models.IntegerField(default=10)),
                ('dia_vencimento', models.IntegerField(default=20)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartoes_pagamento', to='admin_cadastros.estabelecimento')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartoes_pagamento_atualizados', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartoes_pagamento_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cartão de Pagamento',
                'verbose_name_plural': 'Cartões de Pagamento',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='FaturaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField()),
                ('data_fechamento', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('PAGA', 'Paga'), ('PARCIAL', 'Parcialmente Paga')], default='ABERTA', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='appcartao.cartaopagamento')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas_cartao_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas_cartao_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fatura de Cartão',
                'verbose_name_plural': 'Faturas de Cartão',
                'ordering': ['-mes_referencia'],
                'unique_together': {('cartao', 'mes_referencia')},
            },
        ),
        migrations.CreateModel(
            name='TransacaoCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_transacao', models.DateField()),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('nota_fiscal', models.FileField(blank=True, null=True, upload_to='cartao/notas_fiscais/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'peg'])])),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('C', 'Cancelado')], default='A', max_length=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='appcartao.cartaopagamento')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_cartao_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_cartao_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação de Cartão',
                'verbose_name_plural': 'Transações de Cartão',
                'ordering': ['-data_transacao'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_pagamento', models.DateField()),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CHEQUE', 'Cheque'), ('TRANSFERENCIA', 'Transferência'), ('BOLETO', 'Boleto'), ('OUTRO', 'Outro')], max_length=20)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('C', 'Cancelado')], default='A', max_length=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='appcartao.faturacartao')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_cartao_atualizados', to=settings.AUTH_USER_MODEL)),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_cartao_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento de Cartão',
                'verbose_name_plural': 'Pagamentos de Cartão',
                'ordering': ['-data_pagamento'],
            },
        ),
    ]
