BBBBBBB BBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBB

BBBBB BBBBBBBXBBBBBBBB
BBBBB BBBBBBB


XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX

    XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXX


        XXXX XXXXXXXXXXXXXXXXXX XXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXX XXXX XXXXXXXXXXXX
            BB BBBBBBBBBBBBBBB
            BBB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
                XXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
                        XXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXX XXXXXXXXXX
                            XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            BBBBBB
            BBBB
            XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            BBBBB

            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXX
        XXXX
    XXXXXXX


XXXXXX

BBBBBBBB


BBBBB BBBBBBBBBBBB
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXXXXXX

XXXXXXX
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX
        XX XXXX X X XXX XXXXXXXXX XXXX XXXXXXXX XXXXXXXXX XXXX XXX XXX XXXX XXXX XX
    X
XXXXXXXX
BBBBBBBB