BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBB

BBBBB BBBBB
XXXX XXXXX XX XXXX XXXXXXX XXX

XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXXXX


    XXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXX
            FFFFFF
        XXXXXX

        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
                            XXXXXXX
                        XXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
                        XXXXXX
                    XXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXX


XXXXXX
XXXX XXX XXXX XXXXXXX XXX
BBBBBBBB

BBBBB BBBBBBBB

XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXX XXXXX XXXXX XX XXXXXXXXXXXXXX XX XXXXXXXXXXXX XX XXXXXXXXXX XXX XXXXXXXX XXX XXXXXXX XX XXXXXXXXXX XX XXX X XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXX XXXXX XXXXXXXXXX XX XXXXX X XXXXXX XX XXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXX XX XXXXX XXXXXXXXX XX XXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
XXXXXX
XXXX XXX XXXXX XX XXXXXX XXX
BBBBBBBB

BBBBB BBBBB

XXXXXXX
    XX XXXXXXXX X XXXXXXX XXX XXXXXXXXXX XX
    XXXXXXXXXXXXXXX
    XXXXXXXXXXX X
        XX XXXXXX X XXXXXXX XX XXXXXXXX XX
        XXXXXXXXXX XXXXXXXXXXX
        XX XXXXXXXXX XXXXXX X XXXXXXX XX XXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXX XX
        XXXXXXX XX
        XXXXXXXXXXXXXXX XXXXXXX
    X
XXXXXXXX


XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXX

        XXXXX XXXXXXXXXXXXXX
            BBBBBBBBBB



            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                XXXX
                    XXXX
                        XXXX XXXXXXXX XXXX XXXXXXXXXX XXXXX XX XXXXX XXX
                        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXX

                    BB BBBB
                    XXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                            XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXX
                            XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXX XXXXXXXX
                        XXXXXXXXX
                    XXXXX
                    BBBB
                    XXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX
                            XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
                        XXXX
                    XXXXX
                    BBBBB


                    XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX XXXXXXX
                    XXXXXXXXXXXXXXXX XXXXXXXX

                XXXXX
            XXXXXXXX

            XXXXXXX
                BBB BBBB BB BBBBB
                BB BBBB
                XXXX
                    XXXX
                        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXX
                    XXXXX
                    XXXXXXXXX

                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXFFFFFFFFFFF FFFFXXXXX
                    XXXXFFFFFFFFFFF FFFFXXXXX
                    XXXXXXXXX

                XXXXX
                BBBB
                XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                BBBBB
                BBBBBB

            XXXXXXXX
    XXXXXXXX
    XXXXXXX
XXXXXX

BBBBBBBB



BBBBB BBBBBBBB
XXXXXXXXXXXXXXXX
BB BBBBBBBBBBBB
XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX
    XXX XXXXXXXXXXXXXXXXX XXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBB
        XXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBXBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBFFFFFFFFFBBBBBBBXXXXXXXX
                XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBXBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBFFFFFFFFFBBBBBBBXXXXXXX
                XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        BBBBB

        BBB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBB BB B
        XXX XXXXXXXXXXXXXXXX XXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        BBBB B B BBBBBBBBBBBBBBBBBBBBBBBB BBB B B BBBBBBBBBBBBBBBBBBBBBBB XXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBXBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBFFFFFFFFFBBBBBBBXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            BBBBB
            BBBBBB

            BB BBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBXBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBFFFFFFFFFBBBBBBBXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBXBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBFFFFFFFFFBBBBBBBXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            BBBBB
    XXXXX
XXXXXX
BBBBB
XXXXXXX XXXXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBB
XXXXXXXX
    XX XXXXXXXXXX XXXX XXXXXXXXX X XXXXXXX XXX XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
            XXX XXXX XXXXXXXX XX XXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
            X
        XXX
    XXX
XXXXXXXXX

XXXXXXXX
    XX XXXXXX XXXXX XX XXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
        XXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX
XXXXXXXXX

BBBBBBBB