BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBBB

BBBBB BBBBB
XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX

                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

                XXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX
            XXXXXXXXX
        XXXXXX
    XXXXXX


    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                XXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
                XXXXXX
            XXXXXXXXX
        XXXXXX
    XXXXXX

XXXXXX
BBBBBBBB


BBBBB BBBBBBBB
XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXX XXXXX XXXXX XX XXXXXXXXXXXXXX XX XXXXXXXXXXXX XX XXXXXXXXXX XXX XXXXXXXX XXX XXXXXXX XX XXXXXXXXXX XX XXX X XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXX XXXXX XXXXXXXXXX XX XXXXX X XXXXXX XX XXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
XXXXXX
BBBBBBBB
BBBBB BBBBB
XXXXX
    BBB BBBBBBBBBBB BB BBBBBBBBBBBB
    XXXX XXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXX XXXXXX
        XXXX
            XXXXXXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBXX
                 X XXXX
        XXXXX
        XXXX XXXXXXXX XXX XXXXXXXX XXX XXXXXXX XXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXX XXX

        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFF FFFFFFFFFFFXXXX

        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFF FFFFFFFFFFFXXXX

        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFF FFFFFFFFFFFXXXX

        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFF FFFFFFFFFFF XXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFF FFFFFFFFFFF XXX
            FFFFFFFFFFFFFFFFFFFFFFFF FFFFFFFFFFF XXXXX
            FFFFFFFFFFFF FFFFFFFFFFFXXXX

        XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
            FFFFFFFFFFFFFFFFFFFFFFFF FFFFFFFFFFFXXXX

        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFF FFFFFFFFFFFXXXX

        XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX
            FFFFFFFFFFFFFFFFFFFFFFFF FFFFFFFFFFFXXXX

        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XXXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFF FFFFFFFFFFFXXXX

        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFF FFFFFFFFFFFXXXX



    XXXXXX
    BBBBB
    XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
    BBBBBB
XXXXXX
BBBBBBBB
BBBBB BBBBBBBB
XXXXXXXXXXXXXXXX
BB BBBBBBBBBBBB
XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX
    XXX XXXXXXXXXXXXXXXXX XXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBB
        XXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBXXXXXXXX
                XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        BBBBB
        BBB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBB BB B
        XXX XXXXXXXXXXXXXXXX XXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        BBBB B B BBBBBBBBBBBBBBBBBBBBBBBB BBB B B BBBBBBBBBBBBBBBBBBBBBBB XXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            BBBBB
            BBBBBB
            BB BBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            BBBBB
    XXXXX
XXXXXX
BBBBB
BBBBBBBB


BBBBB BBBBBBBBBBBB
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
            XXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X
                XXX XXXXXXXXXXXXX X XXXXXX XX XXXXXXXXX XX XXXXX XXXXXXXX XX XXXXXX X XXXXXXX XXXX X XXXXXXXXX

                XX XXXXXX XXXXXX XXX XXXXXXX XX XXXXXXX XXX XXX XXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXX XXX XXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                        XXXXXXXXXXXXXXX X XXXXXXX XX XXXXXX XXXXX XX XXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                            XX XX X XXXXXXXX XXXXXXXX XX XXXXXX XXXXXXXXXXXX XXXXXXXX X XXXX
                            XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXX X
                                XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
                                    XXXXXXXXXXXXXXX X XXX XX XXXXXX XX XXXXXX XX XXXXXX XX XXXX
                                    XXXXXXXXXXXXX X XXXXX XX XXXXX XXX XX XXXX XXXXX XX XXXXXXXX XXXXXXX XX XXXXXX XXXXXXXXXXX
                                X
                            X
                        X
                    XXX
                X XXXX X
                    XX XX XXXXXXX XXX XXXXXXXXXXXX XXXXXX XXXXXX X XXXXXX XX XXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                        XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXX X
                            XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
                                XXXXXXXXXXXXXXX X XXX
                                XXXXXXXXXXXXX X XXXXX
                            X XXXX X
                                XXXXXXXXXXXXXXX X XXXXXXX
                            X
                        X
                    XXX
                X

                XX XXXXXX X XXXX XXXXXXX XX XXX XXXXXX XXXXXXXXX XX XXXXXX XXXXXXXX
                XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XX X XXXXXXX
            XXX
        XXX

        XX XXXXXX XXXXXXXX XXXX XXXXXXXXXX XX XXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXX X
                XXXX XXXXXXXX XXXXXX XXXXXXXXXX X XXXXXXXXXXXXXXX
                XXXX XXXXXXXX XXXXXX XXXXXXXXXX X XXXXXXXXXXXXXXX
                XXXX XXXXXXXX XXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXX
                XXXXXXXX XXXXXX XXXXXX
            X
        X

        XX XXXXXX XX XXXXXX XXXX X XXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX X
            XXXXXXXXXXXXXXXXXXX XX XXXXXX X XXXXXXXXX XX XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX X XXXXXX
        XXX
    XXX
XXXXXXXXX
BBBBBBBB