BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBB

BBBBB BBBBBBBXBBBBBBBB

BBBBB BBBBB
XXXX XXXXX XX XXXX XXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXXXX

    XXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX



        XXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXX
            FFFFFF
        XXXXXX

        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXX


            XXXX XXXXXXXXXXXX


                XXXX XXXXXXXXXXXXXXXXXX

                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
                            XXXXXXX
                        XXXXXXXXX
                    XXXXXX
                XXXXXX


                XXXX XXXXXXXXXXXXXXXXXX

                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
                            XXXXXX
                        XXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX

        XXXXXX
    XXXXXXX
XXXXXX
XXXX XXX XXXX XXXXXXX XXX
BBBBBBBB


BBBBB BBBBBBBB

XXXX XXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXX XX XXXXXXXXX XX XXXXXXXXXXXXXXX
XXXXXX

XXXX XXX XXXXX XX XXXXXX XXX
BBBBBBBB


BBBBB BBBBB


XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXX


        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX


            XXXX
                XXXX
                    XX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
                    XXXX
                XXXXX
                XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX

                XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXX
            XXXXX

        XXXXXXXX

        XXXXXX XXXXXXXXXXXXXXX
            BBB BBBBBBBB BB BBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXX

                XXXX
                    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXXXXXX
                            XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXX
                    XXXXXX
                XXXXX


                XXXXXXXXX
                XXXXXXXXX


                XXXXFFFFFFFFFFF FFFFXXXXX
                XXXXXXXXX
                XXXXFFFFFFFFFFF FFFFXXXXX

                BB BBBBBBBBBBBBBBBBBBBBBBB
                XXXXXXXXX
                BBBB
                XXXXXXXXX
                BBBBB

                XXXXXXXXX
            XXXXX
            BBBBB
            XXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXX
            BBBBBB
        XXXXXXXX
    XXXXXXXX
XXXXXX
BBBBBBBB



BBBBB BBBBBBBB
XXXXXXXXXXXXXXXX
BB BBBBBBBBBBBB
XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX
    XXX XXXXXXXXXXXXXXXXX XXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBB
        XXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXX
                XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXX
                XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        BBBBB

        BBB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBB BB B
        XXX XXXXXXXXXXXXXXXX XXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        BBBB B B BBBBBBBBBBBBBBBBBBBBBBBB BBB B B BBBBBBBBBBBBBBBBBBBBBBB XXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            BBBBB
            BBBBBB

            BB BBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            BBBBB
    XXXXX
XXXXXX
BBBBB
XXXXXXX XXXXXXXXXXXX
BBBBBBBB