BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BB

BBBBB BBBBBBBXBBBBBBBB


BBBBB BBBBB
XXXXXXXX XXXXXXXXXX

XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXXXX


    XXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXX
            FFFFFF
        XXXXXX

        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
                            XXXXXXX
                        XXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
                        XXXXXX
                    XXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXX


XXXXXX
XXXXXXX XXXX XXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBBB
XXXX XXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX
XXXXXX

BBBBBBBB


BBBBB BBBBB
XXXXXXXXXX XXXX XXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXX


        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX


            XXXX
                XXXXXXXXXXXXXXX
                XXXXXXXXXXX
                XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXX
                XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX
            XXXXX
        XXXXXXXX

        XXXXXX XXXXXXXXXXXXXXX
            BBB BBBBBBBBBBB BB BBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXX

                XXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXXXXXX
                            XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXX
                    XXXXXX
                XXXXX


                XXXXXXXXX
                XXXXXXXXX
                XXXXFFFFFFFFFFFFFFFFFFFFF FXXXXX
                XXXXFFFFFFFFF FXXXXX
                XXXXXXXXX
                XXXXFFFFFFFFFFF FFFFXXXXX
                XXXXFFFFFFFFFFF FFFFXXXXX
                XXXXXXXXX
                XXXXFFFFFFFFFFF FFFFFFFFFFFFF FXXXXX

                BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXXXXXXX
                BBBB
                XXXXXXXXX
                BBBBB

                XXXXXXXXX

            XXXXX
            BBBBB


            XXXX
                XXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXX
            XXXXX
            BBBBBB


        XXXXXXXX
    XXXXXXXX

XXXXXX
XXXXXXX XXXXXX XXXX XXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBBB
XXXXXXXXXXXXXXXX
BB BBBBBBBBBBBB
XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX
    XXX XXXXXXXXXXXXXXXXX XXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBB
        XXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBFFFFFFFFFBBBBBBBXXXXXXXX
                XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBFFFFFFFFFBBBBBBBXXXXXXX
                XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        BBBBB

        BBB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBB BB B
        XXX XXXXXXXXXXXXXXXX XXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        BBBB B B BBBBBBBBBBBBBBBBBBBBBBBB BBB B B BBBBBBBBBBBBBBBBBBBBBBB XXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBFFFFFFFFFBBBBBBBXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            BBBBB
            BBBBBB

            BB BBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBFFFFFFFFFBBBBBBBXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBFFFFFFFFFBBBBBBBXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            BBBBB
    XXXXX
XXXXXX
BBBBB
XXXXXXX XXXXXXXXXXXX
BBBBBBBB