# Generated by Django 4.2.20 on 2026-02-28 20:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimentos', '0001_initial'),
        ('admin_evolucoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('admin_cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextoDocumentoPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('atas', 'Atas'), ('oficios', 'Ofícios'), ('orcamentos', 'Orçamentos')], max_length=20, null=True, verbose_name='Tipo de Documento')),
                ('descricao', models.CharField(max_length=255, unique=True, verbose_name='Descrição Identificadora')),
                ('texto', models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)], verbose_name='Textos Padronizados')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('us_atualizacao', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='textodocpadrao_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='textodocpadrao_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Texto Padrão Documentos',
                'verbose_name_plural': '3. Texto Padrão Documentos',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatorio', models.FileField(upload_to='relatorios/')),
                ('tipo', models.CharField(max_length=10)),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='atendimentos.atendimento')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='GerenciadorRelatorioPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatorio', models.CharField(choices=[('evolucao', 'Evolução'), ('prescricao', 'Prescrição'), ('adep', 'ADEP'), ('sae', 'SAE'), ('sinais_vitais', 'Sinais Vitais'), ('perdas_ganhos', 'Perdas e Ganhos'), ('plano_cuidados', 'Plano de Cuidados'), ('diagnostico', 'Diagnóstico'), ('oficios', 'Ofício'), ('orcamentos', 'Orçamento'), ('atas', 'Ata')], max_length=50)),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('logo_header', models.ImageField(blank=True, help_text='Adicione arquivos dos formatos JPG, JPEG, PNG.', null=True, upload_to='anexos/logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Logotipo')),
                ('dados_header', models.CharField(max_length=255, verbose_name='Título do Relatório')),
                ('dados_right_header', models.CharField(blank=True, max_length=255, null=True, verbose_name='Anotações a direita do cabeçalho')),
                ('dados_footer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dados para rodapé')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento', verbose_name='Estabelecimento')),
                ('tipo_evolucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_evolucoes.tipoevolucao')),
                ('us_atualizacao', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relper_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relper_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Gerenciador de Relatório Personalizado',
                'verbose_name_plural': '1. Gerenciadores de Relatórios Personalizados',
            },
        ),
        migrations.CreateModel(
            name='GerenciadorRelatorioGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_header', models.ImageField(blank=True, help_text='Adicione arquivos dos formatos JPG, JPEG, PNG.', null=True, upload_to='anexos/logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Logotipo')),
                ('dados_header', models.CharField(max_length=255, verbose_name='Título do Relatório')),
                ('dados_right_header', models.CharField(blank=True, max_length=255, null=True, verbose_name='Anotações a direita do cabeçalho')),
                ('dados_footer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dados para rodapé')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento', verbose_name='Estabelecimento')),
                ('us_atualizacao', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relger_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relger_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Gerenciador de Relatório Geral',
                'verbose_name_plural': '2. Gerenciadores de Relatórios Gerais',
            },
        ),
    ]
