# Generated by Django 4.2.20 on 2026-10-06 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos_legais', '0001_initial'),
        ('admin_relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerenciadorrelatoriopersonalizado',
            name='tipo_documento_legal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documentos_legais.tipodocumentolegal', verbose_name='Tipo de Documento Legal'),
        ),
        migrations.AlterField(
            model_name='gerenciadorrelatoriopersonalizado',
            name='relatorio',
            field=models.CharField(choices=[('evolucao', 'Evolução'), ('prescricao', 'Prescrição'), ('adep', 'ADEP'), ('sae', 'SAE'), ('sinais_vitais', 'Sinais Vitais'), ('perdas_ganhos', 'Perdas e Ganhos'), ('plano_cuidados', 'Plano de Cuidados'), ('diagnostico', 'Diagnóstico'), ('oficios', 'Ofício'), ('orcamentos', 'Orçamento'), ('atas', 'Ata'), ('documentos_legais', 'Documentos Legais')], max_length=50),
        ),
    ]
