# Generated by Django 4.2.20 on 2026-02-28 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_cadastros_assistenciais', '0001_initial'),
        ('admin_cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_registro', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Aspecto',
                'verbose_name_plural': '2. Aspectos',
            },
        ),
        migrations.CreateModel(
            name='AspectoAnalisado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('aspecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_sae.aspecto')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_registro', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Aspecto Analisado',
                'verbose_name_plural': '3. Aspectos Analisados',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoEnfermagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Diagnóstico de Enfermagem',
                'verbose_name_plural': '5. Diagnósticos de Enfermagem',
            },
        ),
        migrations.CreateModel(
            name='FatorRelacionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('diagnostico_enfermagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_sae.diagnosticoenfermagem', verbose_name='Diagnóstico de Enfermagem')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_registro', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Fator Relacionado',
                'verbose_name_plural': '6. Fatores Relacionados',
            },
        ),
        migrations.CreateModel(
            name='ParametrosSAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento', verbose_name='Estabelecimento')),
                ('profissao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros_assistenciais.profissao', verbose_name='Profissao SAE')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profissional_sae', to=settings.AUTH_USER_MODEL, verbose_name='Profissional SAE')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_registro', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Parametros SAE',
                'verbose_name_plural': '1. Parametros SAE',
            },
        ),
        migrations.CreateModel(
            name='Intervencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('fator_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_sae.fatorrelacionado', verbose_name='Fator Relacionado')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_registro', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Intervenção',
                'verbose_name_plural': '7. Intervenções',
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('aspecto_analisado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_sae.aspectoanalisado')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_registro', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'Evidência/Característica Definidora',
                'verbose_name_plural': '4. Evidências/Características Definidoras',
            },
        ),
        migrations.AddField(
            model_name='diagnosticoenfermagem',
            name='evidencia',
            field=models.ManyToManyField(to='admin_sae.evidencia'),
        ),
        migrations.AddField(
            model_name='diagnosticoenfermagem',
            name='us_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização'),
        ),
        migrations.AddField(
            model_name='diagnosticoenfermagem',
            name='us_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_registro', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro'),
        ),
    ]
