# Generated by Django 4.2.20 on 2026-02-28 20:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import dominios.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=255, verbose_name='Observações')),
                ('oficio', models.TextField(validators=[django.core.validators.MaxLengthValidator(5500)])),
                ('anexo', models.FileField(blank=True, help_text='Adicione arquivos dos formatos PDF, JPG, JPEG, PNG.', null=True, upload_to='anexos/oficios/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), dominios.utils.validate_anexo_file])),
                ('assinar', models.BooleanField(default=True)),
                ('dt_registro', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Dt.Registro')),
                ('dt_atualizacao', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Dt.Atualização')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_cadastros.estabelecimento')),
                ('us_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oficios_atualizado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Atualização')),
                ('us_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oficios_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Us.Registro')),
            ],
            options={
                'verbose_name': 'oficios',
                'verbose_name_plural': 'oficioss',
                'ordering': ['-pk'],
            },
        ),
    ]
